#!/usr/bin/env bash
# senior-review.sh
# Runs a structured senior-engineer review of recent commits and writes
# findings to REVIEW.md so the Codex agent can read and act on them.
#
# Usage:
#   ./scripts/review-commit.sh              # reviews last commit vs HEAD~1
#   ./scripts/review-commit.sh main         # reviews current branch vs main
#   ./scripts/review-commit.sh HEAD~3 HEAD  # reviews a specific range

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
REVIEW_FILE="$REPO_ROOT/REVIEW.md"
BASE="${1:-HEAD~1}"
HEAD="${2:-HEAD}"

echo "🔍 Generating senior-engineer review: $BASE..$HEAD"

# Gather context
COMMIT_MSG=$(git log "$BASE..$HEAD" --pretty=format:"%h %s" 2>/dev/null || echo "(no commits in range)")
DIFF=$(git diff "$BASE" "$HEAD" 2>/dev/null)
DIFF_STAT=$(git diff "$BASE" "$HEAD" --stat 2>/dev/null)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
AUTHOR=$(git log -1 --pretty=format:"%an <%ae>" 2>/dev/null || echo "unknown")

if [ -z "$DIFF" ]; then
  echo "⚠️  No diff found between $BASE and $HEAD. Nothing to review."
  exit 0
fi

# Write the review prompt context to a temp file for the agy call
PROMPT_FILE=$(mktemp /tmp/review-prompt.XXXXXX.md)

cat > "$PROMPT_FILE" << PROMPT
You are a senior engineer on a permission-safe AI knowledge graph system.
Your job is to review the following code changes and write a structured review.

Project context:
- Stack: Django + DRF + Celery + Neo4j + SpiceDB + Redis + Postgres
- Core constraint: Permission-safe retrieval — restricted facts must never reach the LLM
- Every graph node/relationship/chunk needs source provenance
- SpiceDB is mandatory for authorization — no custom Postgres permission checks
- See AGENTS.md and ai-context/ for full rules

Commits being reviewed:
$COMMIT_MSG

Author: $AUTHOR

Diff stat:
$DIFF_STAT

Full diff:
\`\`\`diff
$DIFF
\`\`\`

Write your review in this exact format:

## Senior Engineer Review
**Timestamp:** $TIMESTAMP
**Commits:** $COMMIT_MSG
**Author:** $AUTHOR

### Summary
(2-3 sentence overview of what the change does)

### ✅ What's Good
(bullet list — what's done correctly, good patterns, good tests, etc.)

### ❌ Issues — Must Fix
(bullet list with file:line references — bugs, security issues, permission leaks, missing provenance, anything that must be fixed before merge)

### ⚠️ Improvements — Should Fix
(bullet list — code quality, test gaps, naming, missing validation, things that should be fixed but aren't blockers)

### 💡 Suggestions — Nice To Have
(bullet list — optional improvements, future considerations)

### Verdict
One of: ✅ APPROVE | 🔄 APPROVE WITH NOTES | ❌ REQUEST CHANGES

### Codex Action Items
(numbered list of concrete tasks for the Codex agent to work through, ordered by priority)
PROMPT

# Run the review via agy if available, otherwise write a placeholder
REVIEW_CONTENT=""

if command -v agy &> /dev/null; then
  echo "  Running agy review..."
  REVIEW_CONTENT=$(agy --no-interactive < "$PROMPT_FILE" 2>/dev/null || echo "")
fi

# If agy failed or isn't available, write a manual-review placeholder
if [ -z "$REVIEW_CONTENT" ]; then
  REVIEW_CONTENT="## Senior Engineer Review
**Timestamp:** $TIMESTAMP
**Commits:** $COMMIT_MSG
**Author:** $AUTHOR

> ⚠️ Automated review could not run (agy not available or failed).
> Run \`agy\` manually with the prompt in \`/tmp/review-prompt.*.md\` or use \`make review\`.

### Diff Stat
\`\`\`
$DIFF_STAT
\`\`\`

### Full Diff
\`\`\`diff
$DIFF
\`\`\`
"
fi

# Write the review file
cat > "$REVIEW_FILE" << REVIEW
<!-- AUTO-GENERATED BY scripts/review-commit.sh — DO NOT EDIT MANUALLY -->
<!-- Codex: read this file before your next task. Address all action items. -->

$REVIEW_CONTENT
REVIEW

rm -f "$PROMPT_FILE"

echo "✅ Review written to REVIEW.md"
echo "   Codex should read REVIEW.md and address action items before next commit."
