# Generated by Django 5.2.15 on 2026-07-07 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="Primary Google Drive", max_length=120)),
                ("workspace_domain", models.CharField(max_length=255)),
                ("delegated_subject_email", models.EmailField(blank=True, max_length=254)),
                ("service_account_email", models.EmailField(blank=True, max_length=254)),
                (
                    "credential_reference",
                    models.CharField(
                        default="GOOGLE_SERVICE_ACCOUNT_FILE",
                        help_text="Env var or secret reference; not credential JSON.",
                        max_length=255,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("folder", "Folder"), ("shared_drive", "Shared drive")],
                        default="folder",
                        max_length=32,
                    ),
                ),
                ("root_folder_id", models.CharField(blank=True, max_length=255)),
                ("shared_drive_id", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=512)),
                ("mime_type", models.CharField(max_length=255)),
                ("drive_url", models.URLField(blank=True, max_length=2048)),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("modified_time", models.DateTimeField(blank=True, null=True)),
                ("last_metadata_sync_time", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                ("folder_path", models.TextField(blank=True)),
                ("parent_folder_ids", models.JSONField(blank=True, default=list)),
                ("shared_drive_id", models.CharField(blank=True, max_length=255)),
                ("owner_email", models.EmailField(blank=True, max_length=254)),
                ("creator_email", models.EmailField(blank=True, max_length=254)),
                ("source_permissions_version", models.CharField(blank=True, max_length=64)),
                ("last_permission_sync_time", models.DateTimeField(blank=True, null=True)),
                ("retrieval_eligible", models.BooleanField(default=False)),
                (
                    "exclusion_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public_link_not_supported", "Public link not supported"),
                            (
                                "domain_wide_visibility_not_supported",
                                "Domain-wide visibility not supported",
                            ),
                            ("unsupported_mime_type", "Unsupported MIME type"),
                            ("missing_required_metadata", "Missing required metadata"),
                            ("permission_metadata_incomplete", "Permission metadata incomplete"),
                        ],
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_documents",
                        to="integrations.driveconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["title", "drive_file_id"],
            },
        ),
        migrations.CreateModel(
            name="DrivePermissionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_permissions_version", models.CharField(max_length=64)),
                ("raw_permissions", models.JSONField(blank=True, default=list)),
                ("has_public_link", models.BooleanField(default=False)),
                ("has_domain_visibility", models.BooleanField(default=False)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_snapshot",
                        to="integrations.sourcedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriveSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("folder", "Folder"), ("shared_drive", "Shared drive")],
                        max_length=32,
                    ),
                ),
                ("root_folder_id", models.CharField(blank=True, max_length=255)),
                ("shared_drive_id", models.CharField(blank=True, max_length=255)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("stored_files", models.PositiveIntegerField(default=0)),
                ("skipped_files", models.PositiveIntegerField(default=0)),
                ("error_summary", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_runs",
                        to="integrations.driveconnection",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drive_sync_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="integration_status_6c8f3d_idx"
                    ),
                    models.Index(
                        fields=["scope_type", "root_folder_id", "shared_drive_id"],
                        name="integration_scope_t_8714a7_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(fields=["drive_file_id"], name="integration_drive_f_558013_idx"),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(
                fields=["retrieval_eligible"], name="integration_retriev_285470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(
                fields=["source_permissions_version"], name="integration_source__5f19cc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("connection", "drive_file_id"),
                name="unique_source_document_per_drive_connection",
            ),
        ),
        migrations.AddIndex(
            model_name="drivepermissionsnapshot",
            index=models.Index(
                fields=["source_permissions_version"], name="integration_source__40fb3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drivepermissionsnapshot",
            index=models.Index(
                fields=["has_public_link", "has_domain_visibility"],
                name="integration_has_pub_24f95f_idx",
            ),
        ),
    ]
