# Generated by Django 5.2.15 on 2026-07-07 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDocumentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.BinaryField()),
                ("exported_mime_type", models.CharField(max_length=255)),
                ("content_hash", models.CharField(max_length=128)),
                ("exported_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="integrations.sourcedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["content_hash"], name="integration_content_aa0baa_idx")
                ],
            },
        ),
    ]
