# Generated by Django 5.2.15 on 2026-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_sourcedocumentcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="drive_md5_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
