# Generated by Django 5.2.15 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_sourcedocument_drive_md5_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="graph_extraction_error_summary",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="graph_extraction_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="graph_extraction_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="graph_extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
