# Generated by Django 5.2.15 on 2026-07-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0004_sourcedocument_graph_extraction_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="graph_extraction_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="graph_extraction_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
