# Generated by Django 5.2.15 on 2026-07-11 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0005_sourcedocument_graph_extraction_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("drive_folder_id", models.CharField(max_length=255)),
                ("parent_folder_ids", models.JSONField(blank=True, default=list)),
                ("source_permissions_version", models.CharField(blank=True, max_length=64)),
                ("active_in_scope", models.BooleanField(default=True)),
                ("last_seen_sync_marker", models.CharField(blank=True, max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DriveFolderPermissionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_permissions_version", models.CharField(max_length=64)),
                ("raw_permissions", models.JSONField(blank=True, default=list)),
                ("permissions_complete", models.BooleanField(default=True)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PermissionSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("documents_seen", models.PositiveIntegerField(default=0)),
                ("folders_seen", models.PositiveIntegerField(default=0)),
                ("groups_resolved", models.PositiveIntegerField(default=0)),
                ("relationships_touched", models.PositiveIntegerField(default=0)),
                ("relationships_deleted", models.PositiveIntegerField(default=0)),
                ("documents_verified", models.PositiveIntegerField(default=0)),
                ("documents_excluded", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="drivepermissionsnapshot",
            name="permissions_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="active_in_scope",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="last_seen_sync_marker",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="spicedb_permissions_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="spicedb_revision",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="spicedb_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="exclusion_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public_link_not_supported", "Public link not supported"),
                    (
                        "domain_wide_visibility_not_supported",
                        "Domain-wide visibility not supported",
                    ),
                    ("unsupported_mime_type", "Unsupported MIME type"),
                    ("missing_required_metadata", "Missing required metadata"),
                    ("permission_metadata_incomplete", "Permission metadata incomplete"),
                    ("unsupported_permission", "Unsupported permission"),
                    ("group_membership_unresolved", "Group membership unresolved"),
                    ("inactive_in_scope", "Inactive in selected scope"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(
                fields=["connection", "active_in_scope"], name="integration_connect_90f279_idx"
            ),
        ),
        migrations.AddField(
            model_name="drivefolder",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drive_folders",
                to="integrations.driveconnection",
            ),
        ),
        migrations.AddField(
            model_name="drivefolderpermissionsnapshot",
            name="drive_folder",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_snapshot",
                to="integrations.drivefolder",
            ),
        ),
        migrations.AddField(
            model_name="permissionsyncrun",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permission_sync_runs",
                to="integrations.driveconnection",
            ),
        ),
        migrations.AddField(
            model_name="permissionsyncrun",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_sync_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="drivefolder",
            index=models.Index(
                fields=["connection", "active_in_scope"], name="integration_connect_47d742_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="drivefolder",
            constraint=models.UniqueConstraint(
                fields=("connection", "drive_folder_id"), name="unique_drive_folder_per_connection"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionsyncrun",
            index=models.Index(
                fields=["status", "created_at"], name="integration_status_19583a_idx"
            ),
        ),
    ]
