# Generated by Django 5.2.15 on 2026-07-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_drivefolder_drivefolderpermissionsnapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedocument",
            name="exclusion_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public_link_not_supported", "Public link not supported"),
                    (
                        "domain_wide_visibility_not_supported",
                        "Domain-wide visibility not supported",
                    ),
                    ("unsupported_mime_type", "Unsupported MIME type"),
                    ("missing_required_metadata", "Missing required metadata"),
                    ("permission_metadata_incomplete", "Permission metadata incomplete"),
                    ("unsupported_permission", "Unsupported permission"),
                    ("group_membership_unresolved", "Group membership unresolved"),
                    ("inactive_in_scope", "Inactive in selected scope"),
                    ("no_effective_grants", "No effective grants"),
                ],
                max_length=64,
            ),
        ),
    ]
