# Generated by Django 5.2.15 on 2026-07-11 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0007_source_document_no_effective_grants"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="drivepermissionsnapshot",
            name="integration_source__40fb3f_idx",
        ),
        migrations.RemoveField(
            model_name="drivefolderpermissionsnapshot",
            name="source_permissions_version",
        ),
        migrations.RemoveField(
            model_name="drivepermissionsnapshot",
            name="source_permissions_version",
        ),
    ]
