# Generated by Django 5.2.15 on 2026-07-14 21:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0008_merge_permission_snapshot_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="driveconnection",
            name="authorization_generation",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="driveconnection",
            name="permission_authority",
            field=models.CharField(
                choices=[
                    ("delegated_acl", "Delegated ACL (legacy)"),
                    ("per_user_oauth", "Per-user OAuth"),
                ],
                default="delegated_acl",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="driveconnection",
            name="permission_authority_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GoogleDriveAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("google_issuer", models.CharField(max_length=255)),
                ("google_subject", models.CharField(max_length=255)),
                ("normalized_email", models.EmailField(max_length=254)),
                ("workspace_domain", models.CharField(max_length=255)),
                ("encrypted_refresh_credential", models.BinaryField(default=bytes)),
                (
                    "encryption_key_version",
                    models.CharField(blank=True, editable=False, max_length=32),
                ),
                ("granted_scopes", models.JSONField(blank=True, default=list)),
                ("connection_generation", models.UUIDField(editable=False)),
                ("authorization_generation", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("scope_missing", "Required scope missing"),
                            ("refresh_failed", "Refresh failed"),
                            ("revoked", "Revoked"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="disconnected",
                        max_length=32,
                    ),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_visibility_sync_at", models.DateTimeField(blank=True, null=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="google_drive_authorizations",
                        to="integrations.driveconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDocumentVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("connection_generation", models.UUIDField(editable=False)),
                ("authorization_generation", models.UUIDField(editable=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("verified_visible", "Verified visible"),
                            ("denied", "Denied"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("visibility_sync_marker", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("spicedb_revision", models.CharField(blank=True, max_length=1024)),
                ("spicedb_verified_at", models.DateTimeField(blank=True, null=True)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_visibility",
                        to="integrations.googledriveauthorization",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_visibility_evidence",
                        to="integrations.sourcedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserVisibilitySyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("connection_generation", models.UUIDField(editable=False)),
                ("authorization_generation", models.UUIDField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("documents_considered", models.PositiveIntegerField(default=0)),
                ("documents_verified_visible", models.PositiveIntegerField(default=0)),
                ("documents_denied", models.PositiveIntegerField(default=0)),
                ("documents_unknown", models.PositiveIntegerField(default=0)),
                ("relationships_touched", models.PositiveIntegerField(default=0)),
                ("relationships_deleted", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visibility_sync_runs",
                        to="integrations.googledriveauthorization",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_visibility_sync_runs",
                        to="integrations.driveconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="googledriveauthorization",
            index=models.Index(
                fields=["connection", "normalized_email", "status"],
                name="integration_connect_0a9994_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="googledriveauthorization",
            index=models.Index(
                fields=["connection", "connection_generation"],
                name="integration_connect_bb8783_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="googledriveauthorization",
            constraint=models.UniqueConstraint(
                fields=("connection", "google_issuer", "google_subject"),
                name="unique_google_drive_authorization_per_connection_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="userdocumentvisibility",
            index=models.Index(
                fields=["authorization", "state", "checked_at"],
                name="integration_authori_b2b533_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userdocumentvisibility",
            index=models.Index(
                fields=["source_document", "connection_generation", "authorization_generation"],
                name="integration_source__63b588_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdocumentvisibility",
            constraint=models.UniqueConstraint(
                fields=("authorization", "source_document"),
                name="unique_user_visibility_per_authorization_document",
            ),
        ),
        migrations.AddIndex(
            model_name="uservisibilitysyncrun",
            index=models.Index(
                fields=["authorization", "status", "created_at"],
                name="integration_authori_2b3de6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uservisibilitysyncrun",
            index=models.Index(
                fields=["connection", "status", "created_at"], name="integration_connect_93947f_idx"
            ),
        ),
    ]
